contentColumnType: text
fieldGroup: acc7548f-3022-405c-b653-2c8760879e60 # Common
handle: firstName
instructions: ''
name: 'First Name'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
